### ISSUE TITLE
Add 3d cursor as a reference standard

### ISSUE THREAD

**Issue by chenpaner** [Pullusb/SB_ground_objects#1]
Is it possible to add a 3d cursor as a reference standard？

**Comment by Pullusb** [comment]
Do you have money?...

I'm kidding 😄ahah!

Hi ! Yes everything is possible.
And since this should be relatively easy to implement, I'll add it soon (If by _reference standard_ you mean use the 3d cursor heights as ground level)

**Comment by Pullusb** [comment]
it's done.
There is now a new `On 3d Cursor` checkbox, it's even active by default ;)

Instead of a basic "ground", this is looking more and more like the object alignment addon I wanted to make since forever.
It might become just that.
